In [1]:
from scipy.optimize import basinhopping
from scipy.optimize import fmin_bfgs
import numpy as np
from math import tanh
import pandas as pd

In [3]:
pnl = pd.read_pickle(u'D:/Data/fund/comp_rpt/安信基金管理有限责任公司.pkl')

In [4]:
pnl.minor_xs('prt_stocktonav')

000310.OF  000335.OF  000433.OF  000577.OF  000974.OF  001185.OF  \
2010-03-31        NaN        NaN        NaN        NaN        NaN        NaN   
2010-06-30        NaN        NaN        NaN        NaN        NaN        NaN   
2010-09-30        NaN        NaN        NaN        NaN        NaN        NaN   
2010-12-31        NaN        NaN        NaN        NaN        NaN        NaN   
2011-03-31        NaN        NaN        NaN        NaN        NaN        NaN   
2011-06-30        NaN        NaN        NaN        NaN        NaN        NaN   
2011-09-30        NaN        NaN        NaN        NaN        NaN        NaN   
2011-12-31        NaN        NaN        NaN        NaN        NaN        NaN   
2012-03-31        NaN        NaN        NaN        NaN        NaN        NaN   
2012-06-30        NaN        NaN        NaN        NaN        NaN        NaN   
2012-09-30        NaN        NaN        NaN        NaN        NaN        NaN   
2012-12-31        NaN        NaN        NaN        NaN        NaN        NaN   
2013-03-31        NaN        NaN        NaN        NaN        NaN        NaN   
2013-06-30        NaN        NaN        NaN        NaN        NaN        NaN   
2013-09-30        NaN        NaN        NaN        NaN        NaN        NaN   
2013-12-31        NaN        NaN        NaN        NaN        NaN        NaN   
2014-03-31        0.0        0.0   1.946170        NaN        NaN        NaN   
2014-06-30        0.0        0.0   8.076488  44.069477        NaN        NaN   
2014-09-30        0.0        0.0   9.318878  82.244156        NaN        NaN   
2014-12-31        0.0        0.0   7.131865  87.358009        NaN        NaN   
2015-03-31        0.0        0.0   4.906869  88.987541        NaN        NaN   
2015-06-30        0.0        0.0   1.724837  90.962059  87.420601   0.689170   
2015-09-30        0.0        0.0  63.269989  87.080223  88.295746   2.588652   
2015-12-31        0.0        0.0  89.510185  85.828445  79.610596   2.401480   
2016-03-31        0.0        0.0  85.428192  90.054001  91.290154   4.714814   
2016-06-30        0.0        0.0  81.503021  92.151756  91.827003   5.134358   
2016-09-30        0.0        0.0  85.578148  93.140724  91.519302  10.236783   
2016-12-31        0.0        0.0  85.821220  91.723267  90.822411  20.069967   
2017-03-31        0.0        0.0  94.638535  93.733902  89.504524  32.410378   
2017-06-30        0.0        0.0  93.317238  92.677826  93.621063  29.782269   
2017-09-30        0.0        0.0  88.622688  92.084778  91.786713  39.606853   

            001287.OF  001316.OF  001338.OF  001399.OF    ...      004393.OF  \
2010-03-31        NaN        NaN        NaN        NaN    ...            NaN   
2010-06-30        NaN        NaN        NaN        NaN    ...            NaN   
2010-09-30        NaN        NaN        NaN        NaN    ...            NaN   
2010-12-31        NaN        NaN        NaN        NaN    ...            NaN   
2011-03-31        NaN        NaN        NaN        NaN    ...            NaN   
2011-06-30        NaN        NaN        NaN        NaN    ...            NaN   
2011-09-30        NaN        NaN        NaN        NaN    ...            NaN   
2011-12-31        NaN        NaN        NaN        NaN    ...            NaN   
2012-03-31        NaN        NaN        NaN        NaN    ...            NaN   
2012-06-30        NaN        NaN        NaN        NaN    ...            NaN   
2012-09-30        NaN        NaN        NaN        NaN    ...            NaN   
2012-12-31        NaN        NaN        NaN        NaN    ...            NaN   
2013-03-31        NaN        NaN        NaN        NaN    ...            NaN   
2013-06-30        NaN        NaN        NaN        NaN    ...            NaN   
2013-09-30        NaN        NaN        NaN        NaN    ...            NaN   
2013-12-31        NaN        NaN        NaN        NaN    ...            NaN   
2014-03-31        NaN        NaN        NaN        NaN    ...            NaN   
2014-06-30 

In [7]:
func = lambda x: np.cos(14.5 * x - 0.3) + (x + 0.2) * x

In [8]:
x0=[1.]

In [9]:
minimizer_kwargs = {"method": "BFGS"}

In [10]:
ret = basinhopping(func, x0, minimizer_kwargs=minimizer_kwargs, niter=200)

In [13]:
print("global minimum: x = %.4f, f(x0) = %.4f" % (ret.x, ret.fun))

global minimum: x = -0.1951, f(x0) = -1.0009


In [16]:
def rosen(x):
   return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:1])**2.0)

In [17]:
def rosen_der(x):
   xm = x[1:-1]
   xm_m1 = x[:-2]
   xm_p1 = x[2:]
   der = np.zeros_like(x)
   der[1:-1] = 200*(xm-xm_m1**2) - 400*(xm_p1 - xm**2)*xm - 2*(1-xm)
   der[0] = -400*x[0]*(x[1]-x[0]**2) - 2*(1-x[0])
   der[-1] = 200*(x[-1]-x[-2]**2)
   return der

In [18]:
x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])

In [19]:
res = fmin_bfgs(rosen, x0, fprime=rosen_der)

         Current function value: 0.004375
         Iterations: 11
         Function evaluations: 60
         Gradient evaluations: 48


In [20]:
print res

[ 0.96718533  0.93491937  0.8737073   0.76378102  0.58305352]


In [31]:
def f(x):
    return -(f1(x[0]) + f2(x[1]))  # -ve sign for maximization


def f1(x):
    return tanh(x)


def f2(x):
    return (10 ** (0.2 * x))

# Starting point
x0 = [1., 1.]

# Bounds
xmin = [1., 1.]
xmax = [2., 2.]


# rewrite the bounds in the way required by L-BFGS-B
bounds = [(low, high) for low, high in zip(xmin, xmax)]

In [32]:
minimizer_kwargs = dict(method="L-BFGS-B", bounds=bounds)

In [33]:
result = basinhopping(f,
                      x0,
                      minimizer_kwargs=minimizer_kwargs,
                      niter=200)

In [34]:
result.x

array([ 2.,  2.])

In [35]:
def constraint1(x):
  return 6 - x[0]

def constraint2(x):
  return 6 - x[0] - x[1]

def constraint3(x):
  return x[0] - 1

In [36]:
c1={"type":"ineq","fun":constraint1}
c2={"type":"ineq","fun":constraint2}
c3={"type":"ineq","fun":constraint3}
minimizer_kwargs = dict(method="COBYLA",constraints=(c1,c2,c3))

In [37]:
result = basinhopping(f,
                      x0,
                      minimizer_kwargs=minimizer_kwargs,
                      niter=200)

In [38]:
result.x

array([ 1.,  5.])